### PR TITLE
Fix incorrect sound volumes for sprinting and walking

### PR DESCRIPTION
**Pull request by Jabka666**
- Fixed by ChronoQuote
- Moved ChannelVolume oustide condition by Jabka

### CODE REVIEW

**Review by Regalis11 — CHANGES_REQUESTED** [review]
Moving ChannelVolume outside the condition doesn't seem safe here, since it's not guaranteed `tempchn` gets assigned a value before ChannelVolume is called.

**Comment by Jabka666** [comment]
> Moving ChannelVolume outside the condition doesn't seem safe here, since it's not guaranteed `tempchn` gets assigned a value before ChannelVolume is called.

image
As you can see, step sound working depends on player ``Shake`` parameter. ``tempchn`` variable has a ``PlaySound_Strict`` in all cases. I checked in debug mode also with artificially high and low FPS. Everything is fine

**Comment by Regalis11** [comment]
What I mean is that the code above has paths that don't assign any value to `tempchn`, for example if `CurrStepSFX` equals to 4. Even if that should not happen, it's better to be safe and not assume there's no bug elsewhere or that no-one ever sets it to 4 for some reason. We could for example verify that tempchn has been assigned a value before attempting to set the volume.

**Comment by Jabka666** [comment]
> What I mean is that the code above has execution paths that don't assign any value to `tempchn`, for example if `CurrStepSFX` equals to 4. Even if that should not happen, it's better to be safe and not assume there's no bug elsewhere or that no-one ever sets it to 4 for some reason. We could for example verify that `tempchn` has been assigned a value before attempting to set the volume.

Well, I added ``If tempchn <> 0 Then`` line. I tried to use new ``Amend`` function. Unfortunately the IDEal Parameters are still here. I apologize for the inconvenience. As you have seen, recent commits no longer had this issue.

**Comment by Regalis11** [comment]
Merged to dev

**Comment by Jabka666** [comment]
> Yes, I think that's better. :) Nitpicky, but better to be safe and ensure this small change can't cause any new MAVs.
> 
> > I tried to use new Amend function
> 
> There's no need to amend the previous commit (and I'd say it's a bad practice, since it "rewrites history" instead of adding the changes in a new commit that ideally explains what was changed and why). In my opinion a better way to add changes to a PR is just to do the new changes as a new commit and push that.

Okay, thanks for info!

**Pull request closed without merging**
