### PR TITLE
Fixes for testroom

### PR DESCRIPTION
**Pull request by Jabka666**
- Fixed LCZ textures in the corridor with DNA door;
- Fixed a hole in the doorway.
Before:
Untitled
After:

### CODE REVIEW

**Review by MemeHoovy — APPROVED** [review]

**Comment by theOneTrueFunniBoi** [comment]
Great Fix! But when i tested it with my mod, it kept throwing entity not found errors. So I worked together some error checking code for the roommesh model loading code, and it turns out that your modified roommesh wants a b3d version of contdoorframe.x. I would try to fix it, but I don't know how to update rmesh files to fix the issue.
image

**Comment by Jabka666** [comment]
> Modified RMesh requests contdoorframe.b3d instead of contdoorframe.x.
> Really got me stumped at first so i wrote some error checking code for it.
> image
> Edit: shortened wording

Never seen this error text

**Comment by Jabka666** [comment]
> Modified RMesh requests contdoorframe.b3d instead of contdoorframe.x. Really got me stumped at first so i wrote some error checking code for it. image Edit: shortened wording

I don't have any problems here

**Comment by theOneTrueFunniBoi** [comment]
> > Modified RMesh requests contdoorframe.b3d instead of contdoorframe.x.
> > Really got me stumped at first so i wrote some error checking code for it.
> > image
> > Edit: shortened wording
> 
> Never seen this error text

That’s because I wrote it specifically to figure out what was throwing the error, because the dumped error logs and debug crash messages are very unhelpful with pin pointing the error.

**Comment by theOneTrueFunniBoi** [comment]
> > Modified RMesh requests contdoorframe.b3d instead of contdoorframe.x. Really got me stumped at first so i wrote some error checking code for it. image Edit: shortened wording
> 
> I don't have any problems here

Weird, perhaps your src code was modified to use b3d models instead of directX models? Either way, it was a simple process of hex editing the mesh’s file extension in the room mesh to fix the issue.

**Comment by Jabka666** [comment]
> > > Modified RMesh requests contdoorframe.b3d instead of contdoorframe.x. Really got me stumped at first so i wrote some error checking code for it. image Edit: shortened wording
> > 
> > 
> > I don't have any problems here
> 
> Weird, perhaps your src code was modified to use b3d models instead of directX models? Either way, some simple hex editing did the trick to fix the issue.

There are no any changes in source code

**Comment by theOneTrueFunniBoi** [comment]
> > > > Modified RMesh requests contdoorframe.b3d instead of contdoorframe.x. Really got me stumped at first so i wrote some error checking code for it. image Edit: shortened wording
> > > 
> > > 
> > > I don't have any problems here
> > 
> > 
> > Weird, perhaps your src code was modified to use b3d models instead of directX models? Either way, some simple hex editing did the trick to fix the issue.
> 
> There are no any changes in source code

Well then I’ve got no idea. It might be throwing error logs and your not noticing. It took a second for me to notice, but I noticed because I delete all error logs that are generated to reduce clutter.

**Comment by Jabka666** [comment]
I'll reopen this PR

**Pull request closed without merging**
