### PR TITLE
Added more EntityY checking for exit1 (Reopen)

### PR DESCRIPTION
**Pull request by Jabka666**
Made a lower part of the Gate B as a regular room on the map

P.S. Wow, GitHub added ``Amend`` function!

### CODE REVIEW

**Comment by Regalis11** [comment]
I'm not sure I understand the changes, which issue does this address?

**Comment by Jabka666** [comment]
> I'm not sure I understand the changes, which issue does this address?

exit1 is a room that have a lower location (connected to the map) and upper location (ending area). This commit fully separates locations.
Example #1: you can't inside lower location;
Example #2: ambient light doesn't work correctly inside lower location and etc...

**Comment by Regalis11** [comment]
I think this check should be consolidated into a single function instead of defining it in multiple places, for example something like 
`Function IsPlayerOutsideFacility%()`

**Comment by Jabka666** [comment]
Good idea

**Review by Regalis11 — CHANGES_REQUESTED** [review]
I think this check should be consolidated into a single function instead of repeating the same code in multiple places, for example something like
`Function IsPlayerOutsideFacility%()`

**Comment by ChronoQuote** [comment]
There is already a function called `CheckForPlayerInFacility` which updates the global `InFacility` every frame during gameplay.

https://github.com/Regalis11/scpcb/blob/53ec858564d2e05baf3313e2f73fb025ee5a7497/Main.bb#L11631-L11647

**Comment by Regalis11** [comment]
I still think it'd be better to consolidate all these checks into one place - and since there seems to be an existing variable keeping track of whether the player is in the facility, it seems that'd be the appropriate thing to use. I won't be accepting this PR in the current form.

**Pull request closed without merging**
