### PR TITLE
Fixes to achievements and "SCPs encountered"

### PR DESCRIPTION
**Pull request by Jabka666**
- Fix achievement order and update DrawEnding to make "SCPs encountered" value more accurate; now 066 and 990 are the only SCPs missing from the total because they don't have achievements
- Capitalization and punctuation corrections to achievement strings
Fixed by ChronoQuote

### CODE REVIEW

**Comment by ChronoQuote** [comment]
I noticed you added an extra capitalization correction to the Butt Ghost achievement, but "James" should remain uncapitalized like it is in [the original article](https://scp-wiki.wikidot.com/scp-789-j).

**Comment by ChronoQuote** [comment]
I also noticed you deleted AchvKeter...

**Comment by Jabka666** [comment]
> I also noticed you deleted AchvKeter...

Bruh

**Comment by Jabka666** [comment]
> I noticed you added an extra capitalization correction to the Butt Ghost achievement, but "James" should remain uncapitalized like it is in [the original article](https://scp-wiki.wikidot.com/scp-789-j).

Researcher "James". Isn't "James" a name of a human?

**Comment by ChronoQuote** [comment]
> Researcher "James". Isn't "James" a name of a human?

Yes but the original article is (at least in the SCP universe) written by a child who doesn't know how to capitalize. The achievement name is meant to match the silly signature at the bottom of the original article.

**Pull request closed without merging**
