### PR TITLE
Many changes (read comment)

### PR DESCRIPTION
**Pull request by Veinhelm**
- Sort source code
- Put the userlibs in their own folder to make them easier to copy
- Compile the RMesh Model Viewer and Music Player
- Add dist and change_icon batch files
- Update IDEal project file
- Update gitignore
- Add Mavless B3D install
- Add resolution limit remover
- Update startup logos
- Update 1123 label to green version (last one before it got deleted)

### CODE REVIEW

**Comment by ChronoQuote** [comment]
> - Add resolution limit remover

IIRC there are issues with screen effects at resolutions above 1080p. In particular, setting the in-game gamma setting to anything other than 100% creates black bars on the sides of the screen. Is that fixed here?

**Comment by Veinhelm** [comment]
I was unaware of that. I have a 1080p monitor and just threw the DLL in there. A past commit _may_ have fixed it but I'm not entirely sure. I've contacted one of my friends with a higher res monitor to test this when they're available to see if it happens.

**Comment by Veinhelm** [comment]
The bug is still present. He got the black bars when he changed the gamma. Might remove the resolution limiter.

**Comment by Jabka666** [comment]
> The bug is still present. They got the black bars when they changed the gamma. It also MAV'd when they tried to run with fullscreen at 1440p. Might remove the resolution limit remover.
It MAV'd because you should increase width and height parameters in the code. 2048 should be 4096
1024 should be 2048 and etc
Better if you'll make a dynamic variable for that

**Comment by Veinhelm** [comment]
I don't have any idea where I do that, since I'm having some trouble navigating the source code. I get what you mean though, I had to do something similar to solve a similar problem with another Blitz game.

**Comment by Veinhelm** [comment]
reopening soon to sync with new merges dev

**Pull request closed without merging**
