### PR TITLE
Fixed smoke.png, closing #121

### PR DESCRIPTION
**Pull request by Saalvage**

### CODE REVIEW

**Comment by MemeHoovy** [comment]
it's the same picture, what's different?

**Comment by ChronoQuote** [comment]
I think Regalis already fixed this in 83101ed.

**Comment by MemeHoovy** [comment]
🤦🏻‍♂️
I'm taking my approval back on this too

**Comment by Saalvage** [comment]
Oh I missed that changes were present on `dev`! What a mess 🥴

**Pull request closed without merging**
